name: tic_tac_toe
description: This is a simple Tic Tac Toe game made with Flutter. It has 2 player and AI feature. The AI is made with the help of Minimax and Alpha-Beta pruning algorithm.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    provider: ^6.0.5
    window_manager: ^0.3.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
